package com.ruanyouzhi.estate.estate.Model;

public class ThumbUp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB_UP.FANS
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    private Long fans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB_UP.COMMENT_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB_UP.QUESTION_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THUMB_UP.COMMENTATOR
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    private Long commentator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB_UP.FANS
     *
     * @return the value of THUMB_UP.FANS
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public Long getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB_UP.FANS
     *
     * @param fans the value for THUMB_UP.FANS
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public void setFans(Long fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB_UP.COMMENT_ID
     *
     * @return the value of THUMB_UP.COMMENT_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB_UP.COMMENT_ID
     *
     * @param commentId the value for THUMB_UP.COMMENT_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB_UP.QUESTION_ID
     *
     * @return the value of THUMB_UP.QUESTION_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB_UP.QUESTION_ID
     *
     * @param questionId the value for THUMB_UP.QUESTION_ID
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THUMB_UP.COMMENTATOR
     *
     * @return the value of THUMB_UP.COMMENTATOR
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THUMB_UP.COMMENTATOR
     *
     * @param commentator the value for THUMB_UP.COMMENTATOR
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }
}