package com.ruanyouzhi.estate.estate.Mapper;

import com.ruanyouzhi.estate.estate.Model.ThumbUp;
import com.ruanyouzhi.estate.estate.Model.ThumbUpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThumbUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    long countByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int deleteByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int deleteByPrimaryKey(Long fans);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int insert(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int insertSelective(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    List<ThumbUp> selectByExampleWithRowbounds(ThumbUpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    List<ThumbUp> selectByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    ThumbUp selectByPrimaryKey(Long fans);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") ThumbUp record, @Param("example") ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int updateByExample(@Param("record") ThumbUp record, @Param("example") ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int updateByPrimaryKeySelective(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THUMB_UP
     *
     * @mbg.generated Tue Dec 17 20:24:41 CST 2019
     */
    int updateByPrimaryKey(ThumbUp record);
}